' Copyright (C) 2019 - present Juergen Zimmermann, Hochschule Karlsruhe
'
' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <https://www.gnu.org/licenses/>.

' Preview durch <Alt>d

@startuml Komponenten

left to right direction

actor RESTClient
actor GraphQLClient

node "Nest" {
  [RequestLoggerMiddleware]

  [PflanzeController]
  [PflanzeResolver]

  [PflanzeService]

  [Repository<Pflanze>]

  [MailService]
}


cloud {
    [TypeORM]
}

cloud {
    [nest-keycloak-connect]
}

cloud {
    [nodemailer]
}

database "DB pflanze" {
    [Tabelle pflanze]
    [Tabelle titel]
    [Tabelle abbildung]
}

node {
    [Keycloak]
}

node {
    [Mailserver]
}

RESTClient ~~> [RequestLoggerMiddleware]
GraphQLClient ~~> [RequestLoggerMiddleware]

[RequestLoggerMiddleware] ~~> [PflanzeController]
[RequestLoggerMiddleware] ~~> [PflanzeResolver]

[PflanzeController] ..> [PflanzeService]
[PflanzeResolver] ..> [PflanzeService]
[PflanzeService] ..> [Repository<Pflanze>]

[Repository<Pflanze>] ~~> [TypeORM]
[TypeORM] ~~> [Tabelle pflanze]
[TypeORM] ~~> [Tabelle titel]
[TypeORM] ~~> [Tabelle abbildung]

[PflanzeController] ..> [nest-keycloak-connect]
[nest-keycloak-connect] ~~> [Keycloak]

[PflanzeService] ..> [MailService]
[MailService] ~~> [nodemailer]
[nodemailer] ~~> [Mailserver]

[MailService] ~[hidden]~> [nest-keycloak-connect]

footer (c) Jürgen Zimmermann

@enduml
